apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: loginwebapp
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: loginwebapp
    spec:
      containers:
      - name: loginwebapp
        image: meghacs/loginwebapp
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
