apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    name: mysql-pod
spec:
  containers:
    - image: santoshpkatageri/mysql-loginwebapp:latest
      name: mysql
      env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "mysql1"
      ports:
        -
          containerPort: 3306 
