apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    name: mysql
    app: mysql-pod
spec:
  selector:
    name: mysql-pod
  ports:
   - port: 3306
     targetPort: 3306
     protocol: TCP
